// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
// import theme style scss file
import '../../style/theme.scss';

export const metadata = {
  title: 'Sunderbanwealdcamp-admin',
  
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  )
}



